import { Poppins } from "next/font/google";
import "../globals.css";
import TanstackProvider from "@/provider/tanstackProvider";
import { SidebarProvider } from "@/components/ui/sidebar";
import AppSidebar from "@/components/shared/Sidebar";
import { Metadata } from "next";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SidebarProvider>
      <AppSidebar />
      {children}
    </SidebarProvider>
         
  );
}
