import { Poppins } from "next/font/google";
import "./globals.css";
import TanstackProvider from "@/provider/tanstackProvider";
import { Toaster } from "sonner";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
 

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <TanstackProvider>
         
          <Toaster
            position="top-center"
            richColors
            closeButton
            duration={4000}
            visibleToasts={3}
            offset={16}
          />
        </TanstackProvider>
      </body>
    </html>
  );
}
